[package]
name = "naildns"
version = "0.2.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2021"
description = """
nailgun (binary called `naildns`) is a small tool written in Rust that supports benchmarking and stress testing DNS servers. It supports IPv4 & IPv6, UDP & TCP and can generate different kinds of queries

ex. naildns 8.8.8.8 -Q 1 		(send 1 query per second to 8.8.8.8)
"""
categories = ["command-line-utilities", "asynchronous", "network-programming"]
keywords = ["nailgun", "dns", "performance", "testing"]
repository = "https://github.com/leshow/nailgun"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["doh"]
doh = ["trust-dns-proto/dns-over-https-rustls", "rustls", "webpki-roots"]

[dependencies]
async-trait = "0.1.51"
anyhow = "1.0"
clap = { version = "3.1.6", features = ["derive"] }
bytes = "1.1"
num_cpus = "1.13.0"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] }
tokio-stream = "0.1.8"
trust-dns-proto = { git = "https://github.com/leshow/trust-dns", branch = "mine_doh" }
trust-dns-resolver = "0.21.2"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.5", features = ["env-filter","json"] }
tracing-appender = "0.2.0"
tracing-futures = "0.2.5"
parking_lot = "0.12.0"
rustc-hash = "1.1.0"
rustls = { version = "0.20.4", optional = true }
rand = "0.8"
governor = "0.4.2"
num-traits = "0.2.14"
webpki-roots = { version = "0.22.3", optional = true }